
language: go

go:
  - 1.8.x

env:
  - GO_ENV=test

before_script:
  - mkdir -p $TRAVIS_BUILD_DIR/public/assets

go_import_path: github.com/glassechidna/codechk

install:
  - glide install

script: buffalo test
